services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
    depends_on:
      - nextjs
    restart: always

volumes:
  certs:
